### ISSUE TITLE
fellow toronto hacker

### ISSUE THREAD

**Issue by sean9999** [niall-byrne/orchestra#4]
hello. Just wanted to say hi. I have heard that the two greatest problems in software engineering are cache invalidation, and [naming things](http://stjosephcontent.github.io/orchestra/).

I enjoy your writing style and approach to solutioning.

**Comment by niall-byrne** [comment]
Everyone is suddenly a classical music fan ... [sigh](https://www.google.ca/?gfe_rd=cr&gws_rd=ssl#q=docker+orchestration)

Thanks for reaching out, back at you with the solutioning, pretty interesting stuff you guys are working on.

**Comment by niall-byrne** [comment]
Noted that orchestra is a super common name for machine management software.
